---

- name: creating users databases (manually)
  mysql_db: 
    db={{ item.value.database['name'] }}
    state=present 
    login_host={{ item.value.database['host'] }}
    login_user=root
  with_dict: '{{stores}}'
  when: item.value.database is defined
  tags:
    - deploy

- name: granting users privileges (manually)
  mysql_user: 
    name: "{{ item.value.database['user'] }}"
    password: "{{ item.value.database['password'] }}" 
    priv: "{{ item.value.database['name'] }}.*:ALL"
    login_host: "{{ item.value.database['host'] }}"
    login_user: root
    # If the database host is specifed, assume it's a remote host and define it here. Else let mysql_user default to localhost
    host: "{{ ansible_default_ipv4.address if (item.value.database['host'] != '') }}"
  with_dict: '{{stores}}'
  when: item.value.database is defined
  tags:
    - deploy

- name: creating users databases (automatically)
  mysql_db: 
    db={{ item.key|replace('.', '_') }} 
    state=present 
    login_user=root 
  with_dict: '{{stores}}'
  when: item.value.database is not defined
  tags:
    - deploy

- name: granting users privileges (automatically)
  mysql_user:
    name={{ item.key|replace('.', '_') }}
    password= "{{ lookup('password', playbook_dir + '/credentials/databases/' + item.key.replace('.', '_') + ' chars=ascii_letters,digits length=16') }}"
    priv={{ item.key|replace('.', '_') }}.*:ALL
    login_user=root
  with_dict: '{{stores}}'
  when: item.value.database is not defined
  tags:
    - deploy
